spring:
 application:
  name: moimeasy

 mail:
  host: smtp.gmail.com
  port: 587
  username: lxxeugene@gmail.com
  password: dwkn aknv bmyz uujy
  properties:
   mail:
    smtp:
     auth: true
     starttls.enable: true
  default-encoding: UTF-8

 jpa:
  hibernate:
   ddl-auto: update
   dialect: org.hibernate.dialect.MySQLDialect
  properties:
   hibernate:
    format_sql: true
  show-sql: true

 datasource:
 # Uncomment and edit the datasource settings if needed
 # driver-class-name: com.mysql.cj.jdbc.Driver
 # username: moimeasy
 # password: moimeasy
 # url: jdbc:mysql://52.79.99.54:3306/moim_easy?characterEncoding=UTF-8&serverTimezone=UTC

 data:
  redis:
   host: localhost
   port: 6379
   # password: 1234

 mvc:
  format:
   time: HH:mm

 profiles:
  include: key

server:
 address: 0.0.0.0 # 모든 IP에서 접근 허용
 port: 8088    # 원하는 포트를 설정 (기본값: 8088)

springdoc:
 default-consumes-media-type: application/json
 default-produces-media-type: application/json
 api-docs:
  groups:
   enabled: true
 swagger-ui:
  operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
  tags-sorter: alpha # 태그 정렬 기준
  path: /swagger-ui.html # html 문서 접속 경로
  disable-swagger-default-url: true
  display-query-params-without-oauth2: true
  doc-expansion: none # tag, operation 펼치는 방식
 paths-to-match:
  - /**
